import Foundation

/// Where a call currently stands. `callId`/`remoteNodeId` are the hex ids needed to
/// address further signaling (`acceptCall`/`rejectCall`/`endCall`) or frames at the
/// right party.
enum CallPhase: Equatable {
    case idle
    case outgoingRinging(remoteNodeId: String, remoteName: String, callId: String, video: Bool)
    case incomingRinging(remoteNodeId: String, remoteName: String, callId: String, video: Bool)
    case active(remoteNodeId: String, remoteName: String, callId: String, video: Bool, startedAt: Date)
}

/// Sentinel `senderId` used for messages/attachments this device sent itself, appended
/// locally (not received back over the mesh) so the sender sees their own outgoing
/// messages in their own chat history too, same as a normal chat app -- rather than only
/// ever seeing what others sent.
let ownMessageSenderId = "me"

/// Lets `DiscoveredPeer` (generated by UniFFI, so we can't add the conformance there) be
/// used with SwiftUI APIs like `.sheet(item:)` and `ForEach` without a separate `id:` key.
extension DiscoveredPeer: Identifiable {
    public var id: String { fullNodeId }
}

/// Thin observable wrapper around the Rust `MeshClient`, polling for incoming messages on
/// a timer since UniFFI's `pollMessage()` is a plain non-blocking call, not a stream.
/// `MeshClient`/`ReceivedMessage` come from the generated `mesh_mobile.swift` file, which
/// is compiled directly into this same app target (no import needed).
@MainActor
final class MeshStore: ObservableObject {
    @Published var messages: [ReceivedMessage] = []
    @Published var isConnected = false
    @Published var nodeId: String = ""
    @Published var lastError: String?
    /// Nearby devices found automatically on the local Wi-Fi network -- like a
    /// Bluetooth/Wi-Fi device picker, no IP address typing required.
    @Published var discoveredPeers: [DiscoveredPeer] = []
    @Published var connectedAddresses: Set<String> = []
    /// Peers we've connected to, keyed by full node id -- kept (not just the address) so
    /// we know who to call and can show a name in the call UI.
    @Published var connectedPeers: [String: DiscoveredPeer] = [:]
    /// Full node ids currently seen in LAN discovery -- i.e. actively broadcasting nearby
    /// right now -- used to show an online/offline indicator per conversation. A peer
    /// drops out of this (and so shows offline) a few seconds after it stops announcing
    /// itself (see `EXPIRE_AFTER` in the Rust discovery code), even if we're still
    /// "connected" to its last-known address.
    @Published var onlinePeerIds: Set<String> = []
    /// Every contact whose cryptographic identity (X25519 key, verified via its Ed25519
    /// binding) is currently known -- keyed by full node id. This is what actually makes
    /// `send`/`sendFile` work: unlike `onlinePeerIds`, this persists for a contact seen
    /// earlier even after they stop broadcasting (e.g. they're offline right now), which
    /// is what lets "MeshTalk Direct Encryption v1" messages still be created for them.
    @Published var contacts: [String: ContactIdentity] = [:]
    /// Full node ids whose cryptographic identity unexpectedly changed since it was
    /// first seen -- surfaced prominently (never silently accepted) until the user
    /// dismisses it. See `ContactEventKind.identityChanged`'s doc.
    @Published var identityChangedPeerIds: Set<String> = []
    /// Live progress for attachments currently being sent or received, keyed by transfer
    /// id -- lets the chat view show a progress bar instead of the attachment appearing
    /// to do nothing until it's 100% there. Entries are removed once a send finishes, or
    /// once the fully-reassembled attachment shows up in `messages`.
    @Published var activeTransfers: [String: TransferProgressUpdate] = [:]
    /// Insertion order for `activeTransfers`, since dictionaries don't preserve one --
    /// keeps multiple concurrent progress bars in a stable order in the UI.
    @Published var activeTransferOrder: [String] = []

    /// Current call state -- drives the incoming-call banner and in-call screen.
    @Published var callPhase: CallPhase = .idle
    /// Latest received remote video frame for an active video call (nil for audio-only).
    @Published var remoteVideoFrame: Data?
    @Published var isMuted = false

    private var client: MeshClient?
    private var pollTimer: Timer?
    private var discoveryTimer: Timer?
    private var callFrameTimer: Timer?
    private var callAudio: CallAudioEngine?
    private(set) var callVideo: CallVideoCapture?

    /// Where the persistent contact cache (Milestone 2B.2a) is stored -- app-private
    /// Application Support storage, which iOS backs up and never exposes to other apps.
    /// A fixed, stable path (not tied to any particular `MeshClient` instance) so a
    /// contact discovered before an app restart is still there afterward.
    private var contactsDbPath: String {
        let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory.appendingPathComponent("contacts.json").path
    }

    /// Where durable replay protection (Milestone 2D) is stored -- separate file from
    /// `contactsDbPath`, same app-private directory. Without this, an attacker (or a
    /// relay redelivering a held copy) could replay an already-processed message just
    /// by waiting for this device to restart.
    private var replayStorePath: String {
        let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory.appendingPathComponent("replay-store.sqlite").path
    }

    /// Where this device's own not-yet-acknowledged outgoing reliable messages and
    /// their retry/backoff state (Milestone 3A) are stored -- without this, a message
    /// still waiting for an ack when the app is killed wouldn't resume retrying after
    /// the next launch.
    private var deliveryStorePath: String {
        let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory.appendingPathComponent("delivery-store.sqlite").path
    }

    /// Where this device's per-neighbor relay-forwarding retry state (Milestone 3B) is
    /// stored -- relevant whenever this device is relaying `DirectV1` traffic for other
    /// devices on the mesh, not only when it's the sender/recipient.
    private var forwardStorePath: String {
        let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory.appendingPathComponent("forward-store.sqlite").path
    }

    /// Where every durably-accepted received message is stored (Milestone 3C) -- the
    /// actual source of truth for chat history, not just an in-memory cache. An
    /// authenticated delivery ack is only ever sent once a message has been durably
    /// written here.
    private var inboxStorePath: String {
        let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory.appendingPathComponent("inbox-store.sqlite").path
    }

    /// Starts a mesh node and immediately starts LAN auto-discovery so nearby devices
    /// running meshtalk on the same Wi-Fi network show up on their own -- connecting to
    /// one is then a single tap (`connect(to:)`) instead of typing an IP address.
    func start(displayName: String, listenPort: UInt16, channel: String) {
        disconnect()
        do {
            // Milestone: bundled into a single `MeshClientConfig` record (rather than
            // one constructor parameter per field) to work around a known, unresolved
            // upstream uniffi-rs/JNA bug that corrupts many-struct-by-value native
            // calls on Android -- see the doc comment on `MeshClientConfig` in
            // crates/mesh-mobile/src/lib.rs. iOS was never affected by that bug (Swift
            // doesn't go through JNA), but both platforms share this one API.
            let newClient = try MeshClient(config: MeshClientConfig(
                displayName: displayName,
                listenAddr: "0.0.0.0:\(listenPort)",
                peerAddrs: [],
                channelPassphrase: channel,
                ttl: 16,
                identitySeed: IdentityKeychain.loadSeed(),
                contactsDbPath: contactsDbPath,
                replayStorePath: replayStorePath,
                deliveryStorePath: deliveryStorePath,
                forwardStorePath: forwardStorePath,
                inboxStorePath: inboxStorePath,
                inboxStorageKey: IdentityKeychain.loadStorageKey()
            ))
            // Persist the seed regardless of whether it was just generated (first
            // launch) or reused (every launch after) -- keeps this device's NodeId
            // stable across restarts instead of silently becoming a new identity.
            if let seedData = dataFromHex(newClient.identitySeed()) {
                IdentityKeychain.saveSeed(seedData)
            }
            // Milestone 3C.1: same idempotent-every-launch persistence for the inbox
            // at-rest storage key -- losing this makes previously-stored chat history
            // permanently unreadable, so it must be saved immediately, not only on
            // first-ever generation.
            if let storageKeyData = dataFromHex(newClient.inboxStorageKey()) {
                IdentityKeychain.saveStorageKey(storageKeyData)
            }
            try newClient.startDiscovery()
            client = newClient
            nodeId = newClient.nodeId()
            isConnected = true
            lastError = nil
            // Hydrate from whatever the persistent ContactStore already had on disk --
            // e.g. a contact discovered before the app was last killed, or an
            // identity-change warning the user hasn't acknowledged yet -- so both
            // survive this restart instead of only reappearing once discovery happens
            // to see that peer again.
            let restoredContacts = newClient.contacts()
            contacts = Dictionary(uniqueKeysWithValues: restoredContacts.map { ($0.fullNodeId, $0) })
            identityChangedPeerIds = Set(restoredContacts.filter { $0.identityChangePending }.map { $0.fullNodeId })
            // Milestone 3C: chat history lives in the durable inbox, not an in-memory
            // list -- hydrate it from disk instead of starting empty every launch.
            messages = newClient.chatHistory()
            startPolling()
            startDiscoveryPolling()
        } catch {
            lastError = "\(error)"
            isConnected = false
        }
    }

    /// One-tap connect to a device found via auto-discovery -- no manual IP entry.
    func connect(to peer: DiscoveredPeer) {
        client?.addPeer(address: peer.address)
        connectedAddresses.insert(peer.address)
        connectedPeers[peer.fullNodeId] = peer
    }

    /// Fallback for when auto-discovery doesn't find a peer (e.g. different subnet):
    /// still supported, just not the primary path anymore.
    func connectManually(address: String) {
        guard !address.trimmingCharacters(in: .whitespaces).isEmpty else { return }
        client?.addPeer(address: address)
        connectedAddresses.insert(address)
    }

    func disconnect() {
        pollTimer?.invalidate()
        pollTimer = nil
        discoveryTimer?.invalidate()
        discoveryTimer = nil
        client = nil
        isConnected = false
        discoveredPeers = []
        connectedAddresses = []
        connectedPeers = [:]
        onlinePeerIds = []
        contacts = [:]
        identityChangedPeerIds = []
        endActiveCallResources()
        callPhase = .idle
    }

    func send(_ text: String, to peerId: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let client, !trimmed.isEmpty else { return }
        switch client.send(remoteNodeId: peerId, text: text) {
        case .sent:
            messages.append(ReceivedMessage(peerId: peerId, senderId: ownMessageSenderId, messageId: UUID().uuidString, text: trimmed, attachment: nil))
        case .tooLongForReliableText:
            // Milestone 3C: never silently downgrade to a weaker delivery guarantee --
            // tell the user instead of quietly sending best-effort.
            lastError = "Message too long to send reliably -- try a shorter message."
        case .failed:
            lastError = isSecure(peerId)
                ? "Failed to send -- no reachable peers right now."
                : "Secure identity unavailable for this contact -- can't send yet."
        }
    }

    /// Sends an image, video, or voice note. Large attachments (especially video) may
    /// not reliably arrive over many hops -- the mesh has no retransmission -- so this
    /// works best for photos and short voice notes.
    func sendFile(data: Data, fileName: String, mimeType: String, kind: AttachmentKind, to peerId: String) {
        guard let client else { return }
        if !client.sendFile(remoteNodeId: peerId, data: data, fileName: fileName, mimeType: mimeType, kind: kind) {
            lastError = isSecure(peerId)
                ? "Failed to send attachment -- no reachable peers right now."
                : "Secure identity unavailable for this contact -- can't send yet."
            return
        }
        let attachment = FileAttachment(transferId: "", kind: kind, name: fileName, mime: mimeType, data: data)
        messages.append(ReceivedMessage(peerId: peerId, senderId: ownMessageSenderId, messageId: UUID().uuidString, text: nil, attachment: attachment))
    }

    /// Whether this device currently holds a verified cryptographic identity for
    /// `peerId` -- i.e. whether "MeshTalk Direct Encryption v1" can actually be used to
    /// message them right now (their binding was checked before being cached; see
    /// `mesh_transport_udp::discovery`'s doc). `false` means messages to them will fail
    /// closed rather than send -- the UI should show something like "Secure identity
    /// unavailable" rather than a generic send failure.
    func isSecure(_ peerId: String) -> Bool {
        contacts[peerId] != nil
    }

    /// All messages exchanged with one specific conversation partner, in the order they
    /// arrived/were sent -- what a per-contact chat thread shows, instead of one shared
    /// feed of everyone's messages.
    func messages(with peerId: String) -> [ReceivedMessage] {
        messages.filter { $0.peerId == peerId }
    }

    /// A short preview of the most recent message with this peer, for the conversation
    /// list (e.g. "Hey, are you around?" or "Photo" for an attachment).
    func lastMessagePreview(with peerId: String) -> String? {
        guard let last = messages.last(where: { $0.peerId == peerId }) else { return nil }
        if let text = last.text { return text }
        guard let attachment = last.attachment else { return nil }
        switch attachment.kind {
        case .image: return "Photo"
        case .video: return "Video"
        case .voice: return "Voice note"
        case .file: return attachment.name
        }
    }

    /// Whether this peer was seen in the most recent LAN discovery sweep -- i.e. still
    /// actively announcing itself nearby right now.
    func isOnline(_ peerId: String) -> Bool {
        onlinePeerIds.contains(peerId)
    }

    // MARK: - Calling

    /// Places a voice or video call to an already-connected peer. Does nothing if a call
    /// is already in progress.
    func placeCall(to peer: DiscoveredPeer, video: Bool) {
        guard callPhase == .idle, let client else { return }
        guard let callId = client.startCall(remoteNodeId: peer.fullNodeId, video: video) else {
            lastError = "Couldn't start the call."
            return
        }
        callPhase = .outgoingRinging(remoteNodeId: peer.fullNodeId, remoteName: peer.displayName, callId: callId, video: video)
    }

    /// Answers the current incoming call.
    func acceptIncomingCall() {
        guard case let .incomingRinging(remoteNodeId, name, callId, video) = callPhase, let client else { return }
        _ = client.acceptCall(remoteNodeId: remoteNodeId, callId: callId)
        startActiveCall(remoteNodeId: remoteNodeId, name: name, callId: callId, video: video)
    }

    /// Declines the current incoming call.
    func rejectIncomingCall() {
        guard case let .incomingRinging(remoteNodeId, _, callId, _) = callPhase, let client else { return }
        _ = client.rejectCall(remoteNodeId: remoteNodeId, callId: callId)
        callPhase = .idle
    }

    /// Ends the call in progress, or cancels one that hasn't been answered yet.
    func hangUp() {
        defer {
            endActiveCallResources()
            callPhase = .idle
        }
        guard let client else { return }
        switch callPhase {
        case let .active(remoteNodeId, _, callId, _, _), let .outgoingRinging(remoteNodeId, _, callId, _):
            _ = client.endCall(remoteNodeId: remoteNodeId, callId: callId)
        case .incomingRinging, .idle:
            break
        }
    }

    func toggleMute() {
        isMuted.toggle()
        // Muting simply stops forwarding captured frames -- see `startActiveCall`'s
        // audio callback -- rather than needing separate engine start/stop plumbing.
    }

    private func startActiveCall(remoteNodeId: String, name: String, callId: String, video: Bool) {
        callPhase = .active(remoteNodeId: remoteNodeId, remoteName: name, callId: callId, video: video, startedAt: Date())
        isMuted = false

        let audio = CallAudioEngine { [weak self] sequence, data in
            guard let self, !self.isMuted else { return }
            _ = self.client?.sendCallFrame(remoteNodeId: remoteNodeId, callId: callId, media: .audio, sequence: sequence, data: data)
        }
        audio.start()
        callAudio = audio

        if video {
            let capture = CallVideoCapture { [weak self] sequence, data in
                _ = self?.client?.sendCallFrame(remoteNodeId: remoteNodeId, callId: callId, media: .video, sequence: sequence, data: data)
            }
            capture.start()
            callVideo = capture
        }

        callFrameTimer = Timer.scheduledTimer(withTimeInterval: 0.01, repeats: true) { [weak self] _ in
            self?.drainCallFrames()
        }
    }

    private func endActiveCallResources() {
        callFrameTimer?.invalidate()
        callFrameTimer = nil
        callAudio?.stop()
        callAudio = nil
        callVideo?.stop()
        callVideo = nil
        remoteVideoFrame = nil
    }

    private func drainCallFrames() {
        guard let client else { return }
        while let frame = client.pollCallFrame() {
            switch frame.media {
            case .audio:
                callAudio?.play(data: frame.data)
            case .video:
                remoteVideoFrame = frame.data
            }
        }
    }

    private func handleCallEvent(_ event: CallEvent) {
        switch event.kind {
        case let .incomingInvite(video):
            guard callPhase == .idle else {
                // Already on a call -- auto-decline instead of showing a second banner.
                _ = client?.rejectCall(remoteNodeId: event.remoteNodeId, callId: event.callId)
                return
            }
            let name = connectedPeers[event.remoteNodeId]?.displayName ?? event.remoteShortId
            callPhase = .incomingRinging(remoteNodeId: event.remoteNodeId, remoteName: name, callId: event.callId, video: video)
        case .accepted:
            if case let .outgoingRinging(remoteNodeId, name, callId, video) = callPhase, callId == event.callId {
                startActiveCall(remoteNodeId: remoteNodeId, name: name, callId: callId, video: video)
            }
        case .rejected, .ended:
            let currentCallId: String?
            switch callPhase {
            case let .outgoingRinging(_, _, callId, _), let .incomingRinging(_, _, callId, _), let .active(_, _, callId, _, _):
                currentCallId = callId
            case .idle:
                currentCallId = nil
            }
            if currentCallId == event.callId {
                endActiveCallResources()
                callPhase = .idle
            }
        }
    }

    private func startPolling() {
        pollTimer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            self?.drainInbox()
        }
    }

    private func startDiscoveryPolling() {
        discoveryTimer = Timer.scheduledTimer(withTimeInterval: 1.5, repeats: true) { [weak self] _ in
            self?.refreshDiscoveredPeers()
        }
    }

    private func refreshDiscoveredPeers() {
        guard let client else { return }
        discoveredPeers = client.discoveredPeers()
        onlinePeerIds = Set(discoveredPeers.map { $0.fullNodeId })
        drainContactEvents()
    }

    /// Drains new-contact/identity-change news (see `ContactEvent`) and keeps `contacts`
    /// in sync with the Rust-side cache -- called right after `discoveredPeers()` since
    /// that's what actually updates the cache on the Rust side.
    private func drainContactEvents() {
        guard let client else { return }
        var sawChangeOrNewContact = false
        while let event = client.pollContactEvent() {
            sawChangeOrNewContact = true
            if case .identityChanged = event.kind {
                identityChangedPeerIds.insert(event.fullNodeId)
            }
        }
        if sawChangeOrNewContact {
            contacts = Dictionary(uniqueKeysWithValues: client.contacts().map { ($0.fullNodeId, $0) })
        }
    }

    /// Call after showing an "identity changed" warning to the user, so it doesn't keep
    /// reappearing for the same contact once acknowledged. Persists immediately via the
    /// Rust-side `ContactStore` so the acknowledgement itself survives a restart too --
    /// otherwise the warning would come back every time the app relaunches.
    func acknowledgeIdentityChange(for peerId: String) {
        identityChangedPeerIds.remove(peerId)
        _ = client?.acknowledgeIdentityChange(remoteNodeId: peerId)
    }

    private func drainInbox() {
        guard let client else { return }
        // Track transfers that finished *this* poll so a stale progress update from just
        // before completion (still sitting in the queue when the completed message was
        // already drained) doesn't resurrect the progress bar for an attachment that's
        // already fully arrived.
        var justCompleted: Set<String> = []
        while let message = client.pollMessage() {
            if let transferId = message.attachment?.transferId {
                removeActiveTransfer(transferId)
                justCompleted.insert(transferId)
            }
            // Milestone 3C: `mesh-core` already durably persisted this message (to
            // `inboxStorePath`) and, for a `DirectV1` message, already acknowledged it
            // to the sender -- there is nothing left to do here to make it durable.
            messages.append(message)
        }
        while let progress = client.pollTransferProgress() {
            if justCompleted.contains(progress.transferId) { continue }
            if progress.doneChunks >= progress.totalChunks {
                removeActiveTransfer(progress.transferId)
                justCompleted.insert(progress.transferId)
            } else {
                if activeTransfers[progress.transferId] == nil {
                    activeTransferOrder.append(progress.transferId)
                }
                activeTransfers[progress.transferId] = progress
            }
        }
        while let event = client.pollCallEvent() {
            handleCallEvent(event)
        }
    }

    private func removeActiveTransfer(_ transferId: String) {
        activeTransfers.removeValue(forKey: transferId)
        activeTransferOrder.removeAll { $0 == transferId }
    }
}
