import Foundation

/// Where a call currently stands. `callId`/`remoteNodeId` are the hex ids needed to
/// address further signaling (`acceptCall`/`rejectCall`/`endCall`) or frames at the
/// right party.
enum CallPhase: Equatable {
    case idle
    case outgoingRinging(remoteNodeId: String, remoteName: String, callId: String, video: Bool)
    case incomingRinging(remoteNodeId: String, remoteName: String, callId: String, video: Bool)
    case active(remoteNodeId: String, remoteName: String, callId: String, video: Bool, startedAt: Date)
}

/// Sentinel `senderId` used for messages/attachments this device sent itself, appended
/// locally (not received back over the mesh) so the sender sees their own outgoing
/// messages in their own chat history too, same as a normal chat app -- rather than only
/// ever seeing what others sent.
let ownMessageSenderId = "me"

/// Lets `DiscoveredPeer` (generated by UniFFI, so we can't add the conformance there) be
/// used with SwiftUI APIs like `.sheet(item:)` and `ForEach` without a separate `id:` key.
extension DiscoveredPeer: Identifiable {
    public var id: String { fullNodeId }
}

/// Thin observable wrapper around the Rust `MeshClient`, polling for incoming messages on
/// a timer since UniFFI's `pollMessage()` is a plain non-blocking call, not a stream.
/// `MeshClient`/`ReceivedMessage` come from the generated `mesh_mobile.swift` file, which
/// is compiled directly into this same app target (no import needed).
@MainActor
final class MeshStore: ObservableObject {
    @Published var messages: [ReceivedMessage] = []
    @Published var isConnected = false
    @Published var nodeId: String = ""
    @Published var lastError: String?
    /// Nearby devices found automatically on the local Wi-Fi network -- like a
    /// Bluetooth/Wi-Fi device picker, no IP address typing required.
    @Published var discoveredPeers: [DiscoveredPeer] = []
    @Published var connectedAddresses: Set<String> = []
    /// Peers we've connected to, keyed by full node id -- kept (not just the address) so
    /// we know who to call and can show a name in the call UI.
    @Published var connectedPeers: [String: DiscoveredPeer] = [:]
    /// Full node ids currently seen in LAN discovery -- i.e. actively broadcasting nearby
    /// right now -- used to show an online/offline indicator per conversation. A peer
    /// drops out of this (and so shows offline) a few seconds after it stops announcing
    /// itself (see `EXPIRE_AFTER` in the Rust discovery code), even if we're still
    /// "connected" to its last-known address.
    @Published var onlinePeerIds: Set<String> = []
    /// Live progress for attachments currently being sent or received, keyed by transfer
    /// id -- lets the chat view show a progress bar instead of the attachment appearing
    /// to do nothing until it's 100% there. Entries are removed once a send finishes, or
    /// once the fully-reassembled attachment shows up in `messages`.
    @Published var activeTransfers: [String: TransferProgressUpdate] = [:]
    /// Insertion order for `activeTransfers`, since dictionaries don't preserve one --
    /// keeps multiple concurrent progress bars in a stable order in the UI.
    @Published var activeTransferOrder: [String] = []

    /// Current call state -- drives the incoming-call banner and in-call screen.
    @Published var callPhase: CallPhase = .idle
    /// Latest received remote video frame for an active video call (nil for audio-only).
    @Published var remoteVideoFrame: Data?
    @Published var isMuted = false

    private var client: MeshClient?
    private var pollTimer: Timer?
    private var discoveryTimer: Timer?
    private var callFrameTimer: Timer?
    private var callAudio: CallAudioEngine?
    private(set) var callVideo: CallVideoCapture?

    /// Starts a mesh node and immediately starts LAN auto-discovery so nearby devices
    /// running meshtalk on the same Wi-Fi network show up on their own -- connecting to
    /// one is then a single tap (`connect(to:)`) instead of typing an IP address.
    func start(displayName: String, listenPort: UInt16, channel: String) {
        disconnect()
        do {
            let newClient = try MeshClient(
                displayName: displayName,
                listenAddr: "0.0.0.0:\(listenPort)",
                peerAddrs: [],
                channelPassphrase: channel,
                ttl: 16
            )
            try newClient.startDiscovery()
            client = newClient
            nodeId = newClient.nodeId()
            isConnected = true
            lastError = nil
            startPolling()
            startDiscoveryPolling()
        } catch {
            lastError = "\(error)"
            isConnected = false
        }
    }

    /// One-tap connect to a device found via auto-discovery -- no manual IP entry.
    func connect(to peer: DiscoveredPeer) {
        client?.addPeer(address: peer.address)
        connectedAddresses.insert(peer.address)
        connectedPeers[peer.fullNodeId] = peer
    }

    /// Fallback for when auto-discovery doesn't find a peer (e.g. different subnet):
    /// still supported, just not the primary path anymore.
    func connectManually(address: String) {
        guard !address.trimmingCharacters(in: .whitespaces).isEmpty else { return }
        client?.addPeer(address: address)
        connectedAddresses.insert(address)
    }

    func disconnect() {
        pollTimer?.invalidate()
        pollTimer = nil
        discoveryTimer?.invalidate()
        discoveryTimer = nil
        client = nil
        isConnected = false
        discoveredPeers = []
        connectedAddresses = []
        connectedPeers = [:]
        endActiveCallResources()
        callPhase = .idle
    }

    func send(_ text: String, to peerId: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let client, !trimmed.isEmpty else { return }
        if !client.send(remoteNodeId: peerId, text: text) {
            lastError = "Failed to send -- no reachable peers right now."
            return
        }
        messages.append(ReceivedMessage(peerId: peerId, senderId: ownMessageSenderId, text: trimmed, attachment: nil))
    }

    /// Sends an image, video, or voice note. Large attachments (especially video) may
    /// not reliably arrive over many hops -- the mesh has no retransmission -- so this
    /// works best for photos and short voice notes.
    func sendFile(data: Data, fileName: String, mimeType: String, kind: AttachmentKind, to peerId: String) {
        guard let client else { return }
        if !client.sendFile(remoteNodeId: peerId, data: data, fileName: fileName, mimeType: mimeType, kind: kind) {
            lastError = "Failed to send attachment -- no reachable peers right now."
            return
        }
        let attachment = FileAttachment(transferId: "", kind: kind, name: fileName, mime: mimeType, data: data)
        messages.append(ReceivedMessage(peerId: peerId, senderId: ownMessageSenderId, text: nil, attachment: attachment))
    }

    /// All messages exchanged with one specific conversation partner, in the order they
    /// arrived/were sent -- what a per-contact chat thread shows, instead of one shared
    /// feed of everyone's messages.
    func messages(with peerId: String) -> [ReceivedMessage] {
        messages.filter { $0.peerId == peerId }
    }

    /// A short preview of the most recent message with this peer, for the conversation
    /// list (e.g. "Hey, are you around?" or "Photo" for an attachment).
    func lastMessagePreview(with peerId: String) -> String? {
        guard let last = messages.last(where: { $0.peerId == peerId }) else { return nil }
        if let text = last.text { return text }
        guard let attachment = last.attachment else { return nil }
        switch attachment.kind {
        case .image: return "Photo"
        case .video: return "Video"
        case .voice: return "Voice note"
        case .file: return attachment.name
        }
    }

    /// Whether this peer was seen in the most recent LAN discovery sweep -- i.e. still
    /// actively announcing itself nearby right now.
    func isOnline(_ peerId: String) -> Bool {
        onlinePeerIds.contains(peerId)
    }

    // MARK: - Calling

    /// Places a voice or video call to an already-connected peer. Does nothing if a call
    /// is already in progress.
    func placeCall(to peer: DiscoveredPeer, video: Bool) {
        guard callPhase == .idle, let client else { return }
        guard let callId = client.startCall(remoteNodeId: peer.fullNodeId, video: video) else {
            lastError = "Couldn't start the call."
            return
        }
        callPhase = .outgoingRinging(remoteNodeId: peer.fullNodeId, remoteName: peer.displayName, callId: callId, video: video)
    }

    /// Answers the current incoming call.
    func acceptIncomingCall() {
        guard case let .incomingRinging(remoteNodeId, name, callId, video) = callPhase, let client else { return }
        _ = client.acceptCall(remoteNodeId: remoteNodeId, callId: callId)
        startActiveCall(remoteNodeId: remoteNodeId, name: name, callId: callId, video: video)
    }

    /// Declines the current incoming call.
    func rejectIncomingCall() {
        guard case let .incomingRinging(remoteNodeId, _, callId, _) = callPhase, let client else { return }
        _ = client.rejectCall(remoteNodeId: remoteNodeId, callId: callId)
        callPhase = .idle
    }

    /// Ends the call in progress, or cancels one that hasn't been answered yet.
    func hangUp() {
        defer {
            endActiveCallResources()
            callPhase = .idle
        }
        guard let client else { return }
        switch callPhase {
        case let .active(remoteNodeId, _, callId, _, _), let .outgoingRinging(remoteNodeId, _, callId, _):
            _ = client.endCall(remoteNodeId: remoteNodeId, callId: callId)
        case .incomingRinging, .idle:
            break
        }
    }

    func toggleMute() {
        isMuted.toggle()
        // Muting simply stops forwarding captured frames -- see `startActiveCall`'s
        // audio callback -- rather than needing separate engine start/stop plumbing.
    }

    private func startActiveCall(remoteNodeId: String, name: String, callId: String, video: Bool) {
        callPhase = .active(remoteNodeId: remoteNodeId, remoteName: name, callId: callId, video: video, startedAt: Date())
        isMuted = false

        let audio = CallAudioEngine { [weak self] sequence, data in
            guard let self, !self.isMuted else { return }
            _ = self.client?.sendCallFrame(remoteNodeId: remoteNodeId, callId: callId, media: .audio, sequence: sequence, data: data)
        }
        audio.start()
        callAudio = audio

        if video {
            let capture = CallVideoCapture { [weak self] sequence, data in
                _ = self?.client?.sendCallFrame(remoteNodeId: remoteNodeId, callId: callId, media: .video, sequence: sequence, data: data)
            }
            capture.start()
            callVideo = capture
        }

        callFrameTimer = Timer.scheduledTimer(withTimeInterval: 0.01, repeats: true) { [weak self] _ in
            self?.drainCallFrames()
        }
    }

    private func endActiveCallResources() {
        callFrameTimer?.invalidate()
        callFrameTimer = nil
        callAudio?.stop()
        callAudio = nil
        callVideo?.stop()
        callVideo = nil
        remoteVideoFrame = nil
    }

    private func drainCallFrames() {
        guard let client else { return }
        while let frame = client.pollCallFrame() {
            switch frame.media {
            case .audio:
                callAudio?.play(data: frame.data)
            case .video:
                remoteVideoFrame = frame.data
            }
        }
    }

    private func handleCallEvent(_ event: CallEvent) {
        switch event.kind {
        case let .incomingInvite(video):
            guard callPhase == .idle else {
                // Already on a call -- auto-decline instead of showing a second banner.
                _ = client?.rejectCall(remoteNodeId: event.remoteNodeId, callId: event.callId)
                return
            }
            let name = connectedPeers[event.remoteNodeId]?.displayName ?? event.remoteShortId
            callPhase = .incomingRinging(remoteNodeId: event.remoteNodeId, remoteName: name, callId: event.callId, video: video)
        case .accepted:
            if case let .outgoingRinging(remoteNodeId, name, callId, video) = callPhase, callId == event.callId {
                startActiveCall(remoteNodeId: remoteNodeId, name: name, callId: callId, video: video)
            }
        case .rejected, .ended:
            let currentCallId: String?
            switch callPhase {
            case let .outgoingRinging(_, _, callId, _), let .incomingRinging(_, _, callId, _), let .active(_, _, callId, _, _):
                currentCallId = callId
            case .idle:
                currentCallId = nil
            }
            if currentCallId == event.callId {
                endActiveCallResources()
                callPhase = .idle
            }
        }
    }

    private func startPolling() {
        pollTimer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            self?.drainInbox()
        }
    }

    private func startDiscoveryPolling() {
        discoveryTimer = Timer.scheduledTimer(withTimeInterval: 1.5, repeats: true) { [weak self] _ in
            self?.refreshDiscoveredPeers()
        }
    }

    private func refreshDiscoveredPeers() {
        guard let client else { return }
        discoveredPeers = client.discoveredPeers()
        onlinePeerIds = Set(discoveredPeers.map { $0.fullNodeId })
    }

    private func drainInbox() {
        guard let client else { return }
        // Track transfers that finished *this* poll so a stale progress update from just
        // before completion (still sitting in the queue when the completed message was
        // already drained) doesn't resurrect the progress bar for an attachment that's
        // already fully arrived.
        var justCompleted: Set<String> = []
        while let message = client.pollMessage() {
            if let transferId = message.attachment?.transferId {
                removeActiveTransfer(transferId)
                justCompleted.insert(transferId)
            }
            messages.append(message)
        }
        while let progress = client.pollTransferProgress() {
            if justCompleted.contains(progress.transferId) { continue }
            if progress.doneChunks >= progress.totalChunks {
                removeActiveTransfer(progress.transferId)
                justCompleted.insert(progress.transferId)
            } else {
                if activeTransfers[progress.transferId] == nil {
                    activeTransferOrder.append(progress.transferId)
                }
                activeTransfers[progress.transferId] = progress
            }
        }
        while let event = client.pollCallEvent() {
            handleCallEvent(event)
        }
    }

    private func removeActiveTransfer(_ transferId: String) {
        activeTransfers.removeValue(forKey: transferId)
        activeTransferOrder.removeAll { $0 == transferId }
    }
}
